[package]
name = "import-http-common"
version = "0.1.0"
edition = "2024"

[lib]
test = false
doctest = false

[features]
test = []

[dependencies]
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["v4", "serde"] }
serde_json = { version = "1.0.149", default-features = false, features = ["std"] }
axum = { version = "0.8.8", default-features = false, features = ["tokio", "http1"] }
reqwest = { version = "0.13.1", default-features = false }
anyhow = { version = "1.0.100", default-features = false }
http-serde = { version = "2.1.1", default-features = false }

[dependencies.common]
path = "../../../common"

[lints]
workspace = true
